[package]
name = "evm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
opt-level = 3
panic = "abort"
codegen-units = 1

[build]
rustflags = ["-C", "target-cpu=native"]